### ISSUE TITLE
Failed to load feeds folder

### ISSUE THREAD

**Issue by sir-brickalot** [arielgee/Sage-Like#2]
After migrating a Firefox profile from MacOS to Linux, Sage-Like throws an error:  
![image](https://user-images.githubusercontent.com/8738891/132259942-e8b168cb-300c-491d-87da-6f9adf0a5524.png)

        Failed to load feeds folder: Error(s) encountered during statement execution: database disk image is malformed.

What I tried: 
- uninstalling/reinstalling the add-on
- delete all traces of of Sage-Like from the profiles folder (but I must have missed something) 
- test a different/new profile -> no problems
- change Feeds Bookmark folder in settings -> not possible, not clickable

**Comment by arielgee** [comment]
I do not think it's a Sage-Like issue.
I’m pretty sure the error message ‘Error(s) encountered during statement execution: database disk image is malformed.’ Is an SQLite database error caused by a problem in the places.sqlite file where Firefox stores the bookmarks and history.
Can you successfully perform other bookmark operations? Like adding a new bookmark or browsing the bookmark manager and moving bookmarks around?
I think the root cause is the profile migration from MacOS to Linux.
I’m not familiar at all with MacOS systems and I don’t know how the migration was performed but may I suggest migrating just the bookmarks in a different way?
Luckily Firefox provide two methods (json and HTML) and I guess that at least one will work.

**Comment by arielgee** [comment]
You're welcome
